### ISSUE TITLE
Merge Conflict in node.yml

### ISSUE THREAD

**Issue by wldcordeiro** [gvillalta99/ansible-nvm#3]
Your node.yml has the remains of a merge conflict within it.

**Comment by kosssi** [comment]
:+1:

**Comment by gvillalta99** [comment]
@wldcordeiro and @kosssi, thank you guys!
I'm not using this repo anymore, so sorry for taking so long to fix this.

**Comment by kosssi** [comment]
Thanks !

What do you use now ?
